@startuml

title UC2: Построение карты воспоминаний (второе посещение)
|Reality|
start
-Установить и подключить\nоборудование
-Опрос пациента
|Doctor UI|
-Заполнение данных\nоб активности мозга
|Server|
-Сохранение данных 

|Reality|
repeat
    fork
        -Задать вопрос
    fork again
        -Показать вещь
    end fork 
    |Doctor UI|
    -Дополнить данные
    |Server|
    -Сохранить изменения 
|Reality|
repeat while (ещё есть\nвопросы\nили вещи?) is (да) not (нет)

-Даём инструкции
|Doctor UI|
-Назначаем дату и время стирания
|Server|
-Сохранить изменения 


stop

@enduml