@startuml МПИ

class пользователь
{
    -логин
    -пароль
}

class "карточка пациента"
{
    -идентификатор
}

class "карточка задачи"
{
}

class "шаблон отчёта"
{
}

class отчёт
{
}

class "карточка оборудования"
{
}

class "шаблон письма"
{
}

class контакт
{
}

class лог
{
}

"шаблон отчёта" ^-- отчёт
"карточка пациента" *-- контакт
"карточка пациента" <-- "карта воспоминаний"
пользователь "1..*" *-- "0..*" "карточка задачи"

@enduml