@startuml

title общая диаграмма деятельности

start

    :получить заявку;
    :провести интервью;

    fork
    :оповестить всех контактов;

    fork again
    :составить карту воспоминаний;

    end fork

    repeat :назначить дату и время стирания
        :повести процедуру стирания воспоминаний;
    repeat while (успешно?) is (нет)

stop

@enduml