@startuml

title UC5: Подготовка к стиранию

start
floating note: **Предусловия**:\n\
  - Карточка пациента\n\
    заполнена\n\
  - Назначено время\n\
    стирания

fork
    -заполняем\nшаблон\nотчёта о\nпроделанной\nработе

fork again
    -получить\nоборудование
    -проверить\nоборудование
    -подойти\nк машине\nзакреплённой\nза бригадой

end fork

stop
floating note: **Постусловия**:\n\
  - Бригада готова\n\
    начинать процедуру\n\
    стирания

@enduml