@startuml

title UC2: Построение карты воспоминаний (второе посещение)

start
floating note: **Предусловия**:\n\
  - Получены вещи, связанные\n\
    с воспоминаниями\n\
  - Сформулированы\n\
    наводящие вопросы\n\
  - Есть валидная (проверенная)\n\
    карточка пациента

fork
    :заполняем\nшаблон\nотчёта о\nпроделанной\nработе;

fork again
    -установить и подключить\nоборудование
    -попросить\nдумать о том,\nчто нужно стереть
    -получить данные\nоб активности\nмозга

    repeat
    if() then
        -показать вещь
        -дополнить данные\nоб активности\nмозга
    else
        -задать вопрос
        -дополнить данные\nоб активности\nмозга
    endif
    repeat while (ещё есть\nвопросы\nили вещи?) is (да)

    -даём инструкции

end fork
-назначаем дату и время стирания

stop
floating note: **Постусловие**:\n\
карта воспоминаний\n\
добавлена в карточку пациента

@enduml