@startuml

title UC3: Информирование контактов пациента

start
floating note: **Предусловие**:\n\
есть валидная (проверенная)\n\
карточка пациента

fork
    :заполняем\nшаблон\nотчёта о\nпроделанной\nработе;

fork again
switch (статус)
    case ( не обработана )
        :позвонить;
    
    case ( договорились\nна повторный звонок )
        :позвонить;
        note right
        **Предусловие**:
        пришло
        назначенное
        время
        end note

    case ( не удалось\nдозвониться )
        :встретиться по\nдомашнему\nадресу;

    case ( не удалось\nвстретиться по\nдомашнему\nадресу )
        :встретиться по\nрабочему\nадресу;

    case ( не удалось\nвстретиться по\nрабочему\nадресу )
        :связаться\nс работодателем;

    case ( не удалось\nсвязаться )
        :проверить\nкорректность\nданных;
        if ("данные верны") then
            :попроcить\nпациента\n\
самостоятельно\nоповестить\nэтот контакт;
            stop
        else (нет)
            - исправить данные
            stop 
        endif

endswitch

end fork
-назначаем дату и время стирания

stop
floating note: **Постусловие**:\n\
сформирован отчёт об оповещении контактов

@enduml