@startuml

title UC4: Процедура стирания воспоминаний

start
floating note: **Предусловия**:\n\
  - Есть карточка пациента\n\
    с назначенным временем\n\
    стирания\n\
  - Есть карта воспоминаний

fork
    :заполняем\nшаблон\nотчёта о\nпроделанной\nработе;

fork again

-приехать на адрес
-дождаться условного знака
-установить и подключить оборудование
-запустить автоматическое стирание
if (завершено успешно) is (нет) then
-связаться с оператором поддержки
else (да)
endif

end fork
-отключить и убрать оборудование
stop

floating note: **Постусловие**:\n\
услуга оказана

@enduml